### ISSUE TITLE
ORI Airlines - Name error for US and USA airline

### ISSUE THREAD

**Issue by lnarboni** [opentraveldata/optd#26] opened 2014-02-25 10:10 UTC
US^USA^US^37^Us Airways^Us Airways^Star Alliance^Member
USA^USA^US^37^Us Airways^Us Airways^Star Alliance^Member

**Comment by da115115** [comment] 2014-02-26 21:28
Duplicate of #27 and #28

**Closed as completed by da115115** 2014-02-26 21:28 UTC
